# Generated by Django 3.2.7 on 2021-11-23 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('category', models.CharField(choices=[('H', 'History'), ('E', 'Educational'), ('R', 'Religious'), ('A', 'Audio Dramas'), ('S', 'Sports'), ('C', 'Comedy Casts'), ('O', 'Society and Culture'), ('F', 'Feminist'), ('L', 'Health'), ('D', 'Advice and Self-Help'), ('B', 'Business'), ('N', 'News and Politics'), ('P', 'Personal Journal'), ('I', 'Interview Cast'), ('V', 'Environment/Science'), ('T', 'Technology'), ('M', 'Crime'), ('K', 'Kids and Families'), ('W', 'Law'), ('U', 'Pop Culture'), ('Y', 'Philosophy'), ('G', 'Games and Hobbies')], default='H', max_length=1)),
                ('link', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recommendationlist',
            name='podcasts',
            field=models.ManyToManyField(to='main_app.Podcast'),
        ),
    ]
