# Generated by Django 3.2.7 on 2021-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
