# Generated by Django 3.2.7 on 2021-11-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_review_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='podcast',
            name='average_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
