# Generated by Django 3.2.7 on 2021-11-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_podcast_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
