# Generated by Django 3.2.7 on 2021-11-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_podcast_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
